# Generated by Django 3.2.13 on 2022-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produced_energy_in_watt', models.CharField(default=0, max_length=32, null=True)),
                ('consumed_energy_in_watt', models.CharField(default=0, max_length=32, null=True)),
                ('hash', models.CharField(default=None, max_length=32, null=True)),
                ('txId', models.CharField(default=None, max_length=66, null=True)),
            ],
        ),
    ]
